name: Build LaTeX

on: 
  workflow_dispatch:
    inputs:
      repository:
        description: 'The directory name where the LaTeX report is located'
        required: true
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra texlive-publishers biber texlive-science

    - name: Compile document
      run: |
        echo -e "changing directory to ${{ inputs.repository }}"
        cd reports/${{ inputs.repository }}
        echo -e "\n===== Generating auxiliary files =====\n"
        pdflatex -interaction=nonstopmode report.tex
        echo -e "\n===== Updating references =====\n"
        biber report
        echo -e "\n===== Using bibliography =====\n"
        pdflatex -interaction=nonstopmode report.tex
        echo -e "\n===== Ensuring consistency =====\n"
        pdflatex -interaction=nonstopmode report.tex
      
    - name: Upload PDF as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: report.pdf
        path: reports/${{ inputs.repository }}/report.pdf